#apiVersion: extensions/v1beta1
#apiVersion: v1
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: jenkins-demo
#  namespace: default#
#spec:
#  template:
#    metadata:
#      labels:
#        app: jenkins-demo
#    spec:
#      containers:
#      - image: kay71029/jenkins-demo:<BUILD_TAG>
#        imagePullPolicy: IfNotPresent
#        name: jenkins-demo
#        env:
#        - name: branch
#          value: <BRANCH_NAME>

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
